import { Order } from '@/types';

export const sampleOrders: Order[] = [
  {
    id: 'ORD-001',
    items: [
      {
        product: {
          id: '1',
          name: 'Classic Navy Blue Oxford Shirt',
          slug: 'classic-navy-blue-oxford-shirt',
          description: '',
          price: 1899,
          images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=200'],
          category: 'Shirts',
          sizes: ['M'],
          colors: [],
          fabric: '',
          fit: '',
          inStock: true,
          rating: 0,
          reviews: 0,
          createdAt: '',
        },
        size: 'M',
        quantity: 2,
      },
    ],
    status: 'shipped',
    shippingAddress: {
      fullName: 'Harshad',
      phone: '9876543210',
      street: '123 Main St, Railway Kodur',
      city: 'Kodur',
      state: 'Andhra Pradesh',
      pincode: '516101',
    },
    paymentMethod: 'Cash on Delivery',
    subtotal: 3798,
    shipping: 0,
    total: 3798,
    createdAt: '2026-07-20T10:30:00Z',
    estimatedDelivery: '2026-07-28',
  },
  {
    id: 'ORD-002',
    items: [
      {
        product: {
          id: '2',
          name: 'Charcoal Grey Luxury Polo',
          slug: 'charcoal-grey-luxury-polo',
          description: '',
          price: 1599,
          images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=200'],
          category: 'Polos',
          sizes: ['L'],
          colors: [],
          fabric: '',
          fit: '',
          inStock: true,
          rating: 0,
          reviews: 0,
          createdAt: '',
        },
        size: 'L',
        quantity: 1,
      },
    ],
    status: 'delivered',
    shippingAddress: {
      fullName: 'Harshad',
      phone: '9876543210',
      street: '123 Main St, Railway Kodur',
      city: 'Kodur',
      state: 'Andhra Pradesh',
      pincode: '516101',
    },
    paymentMethod: 'Razorpay',
    subtotal: 1599,
    shipping: 0,
    total: 1599,
    createdAt: '2026-07-15T14:00:00Z',
    estimatedDelivery: '2026-07-22',
  },
];
