import { Product, Testimonial } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Navy Blue Oxford Shirt',
    slug: 'classic-navy-blue-oxford-shirt',
    description: 'Premium Oxford weave cotton shirt with a modern tailored fit. Features a button-down collar, chest pocket, and adjustable cuffs. Perfect for both casual and semi-formal occasions.',
    price: 1899,
    originalPrice: 2499,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736e10?w=800',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Navy Blue', hex: '#1B2A4A' }, { name: 'White', hex: '#F5F5F5' }],
    fabric: '100% Premium Cotton Oxford',
    fit: 'Modern Tailored Fit',
    inStock: true,
    isNew: true,
    isBestseller: true,
    rating: 4.8,
    reviews: 124,
    createdAt: '2025-12-01',
  },
  {
    id: '2',
    name: 'Charcoal Grey Luxury Polo',
    slug: 'charcoal-grey-luxury-polo',
    description: 'Ultra-soft pique cotton polo with a sleek matte finish. Ribbed collar and cuffs, three-button placket, and a relaxed yet refined silhouette.',
    price: 1599,
    originalPrice: 1999,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
    ],
    category: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }, { name: 'Black', hex: '#0A0A0A' }],
    fabric: 'Premium Pique Cotton',
    fit: 'Regular Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.6,
    reviews: 89,
    createdAt: '2025-11-15',
  },
  {
    id: '3',
    name: 'White Linen Blend Casual Shirt',
    slug: 'white-linen-blend-casual-shirt',
    description: 'Lightweight linen-cotton blend shirt ideal for warm-weather styling. Camp collar, short sleeves, and a relaxed straight hem.',
    price: 1399,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736e10?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#F5F5F5' }, { name: 'Beige', hex: '#D4C9B5' }],
    fabric: '55% Linen, 45% Cotton',
    fit: 'Relaxed Fit',
    inStock: true,
    isNew: true,
    rating: 4.7,
    reviews: 56,
    createdAt: '2026-01-10',
  },
  {
    id: '4',
    name: 'Black Slim Fit Denim Shirt',
    slug: 'black-slim-fit-denim-shirt',
    description: 'Heavyweight denim shirt with a slim, modern silhouette. Western stitching details, snap buttons, and a lived-in wash.',
    price: 2199,
    originalPrice: 2799,
    images: [
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }],
    fabric: '100% Cotton Denim',
    fit: 'Slim Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.5,
    reviews: 72,
    createdAt: '2025-10-20',
  },
  {
    id: '5',
    name: 'Burgundy Textured Polo',
    slug: 'burgundy-textured-polo',
    description: 'Premium textured knit polo with a subtle honeycomb pattern. Mother-of-pearl buttons, tailored collar, and a modern athletic fit.',
    price: 1799,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
    ],
    category: 'T-Shirts',
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Burgundy', hex: '#800020' }, { name: 'Forest Green', hex: '#1B5E20' }],
    fabric: 'Textured Knit Cotton',
    fit: 'Athletic Fit',
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviews: 34,
    createdAt: '2026-01-05',
  },
  {
    id: '6',
    name: 'Olive Green Utility Shirt',
    slug: 'olive-green-utility-shirt',
    description: 'Utility-inspired casual shirt with dual chest pockets, epaulettes, and a relaxed fit. garment-dyed for a soft, lived-in feel.',
    price: 1699,
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736e10?w=800',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Olive Green', hex: '#556B2F' }],
    fabric: '100% Cotton Twill',
    fit: 'Relaxed Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.4,
    reviews: 48,
    createdAt: '2025-09-15',
  },
  {
    id: '7',
    name: 'Cobalt Blue Premium Oxford',
    slug: 'cobalt-blue-premium-oxford',
    description: 'Statement cobalt blue Oxford shirt in premium cotton. A signature ARHUU piece designed for versatility — pair with chinos or denim.',
    price: 1999,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Cobalt Blue', hex: '#0047AB' }],
    fabric: '100% Premium Cotton Oxford',
    fit: 'Modern Tailored Fit',
    inStock: true,
    isNew: true,
    rating: 5.0,
    reviews: 18,
    createdAt: '2026-02-01',
  },
  {
    id: '8',
    name: 'Striped Cotton Casual Shirt',
    slug: 'striped-cotton-casual-shirt',
    description: 'Classic stripe pattern in a soft laundered cotton. Button-down collar, chest pocket, and a versatile cut that works tucked or untucked.',
    price: 1499,
    images: [
      'https://images.unsplash.com/photo-1598033129183-c4f50c736e10?w=800',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Blue Stripe', hex: '#1B2A4A' }, { name: 'Pink Stripe', hex: '#D4A5A5' }],
    fabric: '100% Cotton Poplin',
    fit: 'Regular Fit',
    inStock: true,
    rating: 4.3,
    reviews: 61,
    createdAt: '2025-08-10',
  },
  {
    id: '9',
    name: 'Slim Fit Black Chinos',
    slug: 'slim-fit-black-chinos',
    description: 'Premium stretch cotton chinos with a modern slim fit. Wrinkle-resistant fabric, zip fly, and a versatile silhouette that works from office to evening.',
    price: 1799,
    originalPrice: 2299,
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
    ],
    category: 'Pants',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }, { name: 'Navy', hex: '#1B2A4A' }],
    fabric: '98% Cotton, 2% Elastane',
    fit: 'Slim Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.6,
    reviews: 94,
    createdAt: '2025-11-20',
  },
  {
    id: '10',
    name: 'Beige Cargo Joggers',
    slug: 'beige-cargo-joggers',
    description: 'Relaxed-fit cargo joggers in garment-dyed cotton twill. Elasticated cuffs, side cargo pockets, and an adjustable drawstring waist for all-day comfort.',
    price: 1499,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
    ],
    category: 'Pants',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Beige', hex: '#D4C9B5' }, { name: 'Olive', hex: '#556B2F' }],
    fabric: '100% Cotton Twill',
    fit: 'Relaxed Fit',
    inStock: true,
    isNew: true,
    rating: 4.5,
    reviews: 47,
    createdAt: '2026-01-15',
  },
  {
    id: '11',
    name: 'Premium Heavyweight T-Shirt',
    slug: 'premium-heavyweight-t-shirt',
    description: 'Ultra-heavy 240 GSM cotton t-shirt with a structured fit. Ribbed crew neck, taped shoulders, and a clean hem. The essential everyday tee.',
    price: 999,
    originalPrice: 1299,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    category: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'White', hex: '#F5F5F5' }, { name: 'Black', hex: '#0A0A0A' }, { name: 'Grey', hex: '#808080' }],
    fabric: '100% Premium Cotton',
    fit: 'Regular Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.7,
    reviews: 156,
    createdAt: '2025-10-05',
  },
  {
    id: '12',
    name: 'Graphic Print Oversized Tee',
    slug: 'graphic-print-oversized-tee',
    description: 'Streetwear-inspired oversized t-shirt with a bold graphic print. Drop shoulders, relaxed silhouette, and premium soft-hand fabric.',
    price: 1199,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    category: 'T-Shirts',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }, { name: 'White', hex: '#F5F5F5' }],
    fabric: '100% Cotton Jersey',
    fit: 'Oversized Fit',
    inStock: true,
    isNew: true,
    rating: 4.4,
    reviews: 38,
    createdAt: '2026-02-10',
  },
  {
    id: '13',
    name: 'Classic Full-Zip Hoodie',
    slug: 'classic-full-zip-hoodie',
    description: 'Heavyweight fleece hoodie with a full-zip front. Adjustable drawstring hood, ribbed cuffs and hem, and a front kangaroo pocket.',
    price: 2499,
    originalPrice: 2999,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
    ],
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Charcoal', hex: '#36454F' }, { name: 'Black', hex: '#0A0A0A' }, { name: 'Navy', hex: '#1B2A4A' }],
    fabric: '400 GSM Fleece',
    fit: 'Regular Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.8,
    reviews: 112,
    createdAt: '2025-09-01',
  },
  {
    id: '14',
    name: 'Pullover Essential Hoodie',
    slug: 'pullover-essential-hoodie',
    description: 'Essential pullover hoodie in soft mid-weight fleece. Ribbed cuffs and hem, adjustable hood, and a clean minimalist design.',
    price: 2199,
    images: [
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    ],
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Grey', hex: '#808080' }, { name: 'Black', hex: '#0A0A0A' }],
    fabric: '350 GSM Fleece',
    fit: 'Regular Fit',
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviews: 73,
    createdAt: '2026-01-20',
  },
  {
    id: '15',
    name: 'Slim Track Pants',
    slug: 'slim-track-pants',
    description: 'Performance track pants with a slim athletic silhouette. Moisture-wicking fabric, zip pockets, and tapered cuffs for a clean look.',
    price: 1399,
    originalPrice: 1799,
    images: [
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
    category: 'Tracks',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }, { name: 'Navy', hex: '#1B2A4A' }, { name: 'Grey', hex: '#808080' }],
    fabric: 'Polyester-Cotton Blend',
    fit: 'Slim Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.5,
    reviews: 89,
    createdAt: '2025-11-10',
  },
  {
    id: '16',
    name: 'Jogger Track Pants with Stripes',
    slug: 'jogger-track-pants-stripes',
    description: 'Classic track pants with contrast side stripes. Elasticated waist with drawstring, cuffed ankles, and a relaxed athletic fit.',
    price: 1299,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
    ],
    category: 'Tracks',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Navy', hex: '#1B2A4A' }, { name: 'Black', hex: '#0A0A0A' }],
    fabric: 'Cotton-Polyester Fleece',
    fit: 'Regular Fit',
    inStock: true,
    isNew: true,
    rating: 4.3,
    reviews: 55,
    createdAt: '2026-02-01',
  },
  {
    id: '17',
    name: 'Khaki Flat Front Trousers',
    slug: 'khaki-flat-front-trousers',
    description: 'Smart casual trousers in lightweight cotton twill. Flat front, zip fly, side pockets, and a tailored straight leg fit.',
    price: 1699,
    images: [
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    ],
    category: 'Pants',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Khaki', hex: '#C3B091' }, { name: 'Navy', hex: '#1B2A4A' }],
    fabric: '100% Cotton Twill',
    fit: 'Straight Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.4,
    reviews: 68,
    createdAt: '2025-12-05',
  },
  {
    id: '18',
    name: 'Denim Jeans Slim Stretch',
    slug: 'denim-jeans-slim-stretch',
    description: 'Modern slim stretch denim jeans with a comfortable mid-rise. Five-pocket styling, slight stretch for mobility, and a clean dark wash.',
    price: 1999,
    originalPrice: 2499,
    images: [
      'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=800',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    ],
    category: 'Pants',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Dark Blue', hex: '#1B2A4A' }, { name: 'Black', hex: '#0A0A0A' }],
    fabric: '98% Cotton, 2% Elastane Denim',
    fit: 'Slim Fit',
    inStock: true,
    isNew: true,
    rating: 4.7,
    reviews: 132,
    createdAt: '2026-01-25',
  },
  {
    id: '19',
    name: 'Linen Cotton Tapered Pants',
    slug: 'linen-cotton-tapered-pants',
    description: 'Lightweight linen-cotton blend pants with a tapered leg. Elasticated waist with drawstring, side pockets, and a relaxed summer silhouette.',
    price: 1599,
    images: [
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
    category: 'Pants',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Beige', hex: '#D4C9B5' }, { name: 'White', hex: '#F5F5F5' }],
    fabric: '55% Linen, 45% Cotton',
    fit: 'Tapered Fit',
    inStock: true,
    isNew: true,
    rating: 4.2,
    reviews: 41,
    createdAt: '2026-02-15',
  },
  {
    id: '20',
    name: 'Zip-Up Bomber Hoodie',
    slug: 'zip-up-bomber-hoodie',
    description: 'Bomber-style zip-up hoodie in heavyweight fleece. Ribbed collar and cuffs, front zip closure, and a street-ready silhouette.',
    price: 2799,
    originalPrice: 3299,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
    ],
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }, { name: 'Olive', hex: '#556B2F' }],
    fabric: '420 GSM Fleece',
    fit: 'Regular Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.6,
    reviews: 87,
    createdAt: '2025-11-30',
  },
  {
    id: '21',
    name: 'Oversized Graphic Hoodie',
    slug: 'oversized-graphic-hoodie',
    description: 'Streetwear oversized hoodie with a bold back print. Dropped shoulders, ribbed cuffs, and a cozy brushed fleece interior.',
    price: 2599,
    images: [
      'https://images.unsplash.com/photo-1594930328898-3bb320e2f9dd?w=800',
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    ],
    category: 'Hoodies',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Grey', hex: '#808080' }, { name: 'Black', hex: '#0A0A0A' }],
    fabric: '380 GSM Brushed Fleece',
    fit: 'Oversized Fit',
    inStock: true,
    isNew: true,
    rating: 4.5,
    reviews: 63,
    createdAt: '2026-02-10',
  },
  {
    id: '22',
    name: 'Cotton Blend Track Joggers',
    slug: 'cotton-blend-track-joggers',
    description: 'Everyday track joggers in a soft cotton blend. Elastic waist with drawcord, ribbed cuffs, and two zip side pockets.',
    price: 1199,
    images: [
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
    category: 'Tracks',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Grey', hex: '#808080' }, { name: 'Navy', hex: '#1B2A4A' }],
    fabric: '70% Cotton, 30% Polyester',
    fit: 'Regular Fit',
    inStock: true,
    isBestseller: true,
    rating: 4.4,
    reviews: 79,
    createdAt: '2025-12-20',
  },
  {
    id: '23',
    name: 'Performance Training Tracksuit',
    slug: 'performance-training-tracksuit',
    description: 'Full-zip track jacket with matching joggers. Moisture-wicking fabric, stand collar, and contrast taping for a sporty edge.',
    price: 2999,
    originalPrice: 3999,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
      'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=800',
    ],
    category: 'Tracks',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#0A0A0A' }, { name: 'Navy', hex: '#1B2A4A' }],
    fabric: 'Polyester-Spandex Blend',
    fit: 'Athletic Fit',
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviews: 44,
    createdAt: '2026-02-20',
  },
];

export const categories = [
  { name: 'Shirts', slug: 'shirts', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600', count: 24 },
  { name: 'Pants', slug: 'pants', image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600', count: 18 },
  { name: 'T-Shirts', slug: 't-shirts', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', count: 20 },
  { name: 'Hoodies', slug: 'hoodies', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600', count: 12 },
  { name: 'Tracks', slug: 'tracks', image: 'https://images.unsplash.com/photo-1593032456465-97d2c1f18dd5?w=600', count: 15 },
];

export const testimonials: Testimonial[] = [
  { id: '1', name: 'Vikram Reddy', location: 'Hyderabad', text: 'The fabric quality is outstanding. Bought two Oxford shirts and they feel premium. Definitely my go-to brand now.', rating: 5 },
  { id: '2', name: 'Arun Kumar', location: 'Bangalore', text: 'Love the cobalt blue shirt — the fit is perfect and the color is even better in person. Great for office and evenings.', rating: 5 },
  { id: '3', name: 'Sai Teja', location: 'Chennai', text: 'Fast delivery to Chennai and the linen shirt is perfect for our weather. True to size and well packaged.', rating: 4 },
  { id: '4', name: 'Rahul P', location: 'Mumbai', text: 'ARHUU polos are my new favourite. The charcoal grey one is incredibly soft. Worth every rupee.', rating: 5 },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category.toLowerCase() === category.toLowerCase());
}
